[versions]
agp = "9.0.0"
bottonnavigationview = "1.2.1"
firebaseBom = "34.2.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
pickerimages = "1.1.1"
volley = "1.2.1"

[libraries]
bottonnavigationview = { module = "com.github.AkSoftwareSolution:BottonNavigationView", version.ref = "bottonnavigationview" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
pickerimages = { module = "com.github.AkSoftwareSolution:pickerImages", version.ref = "pickerimages" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

